---
- name: A playbook to deploy a simple openstack network
  hosts: localhost

  vars:
   aop: present
     
  tasks:
  - name: Manage a demo-net network
    os_network:
      cloud: alta3cloud
      state: "{{ aop }}"
      name: demo-net
      external: false

  - name: Manage a demo-net subnet
    os_subnet:
      cloud: alta3cloud
      state: "{{ aop }}"
      network_name: demo-net
      name: demo-net-subnet
      cidr: 192.168.30.0/24
      dns_nameservers:
        - 10.0.0.1
      gateway_ip: 192.168.30.1

  - name:  Manage a demorouter router
    os_router:
      state: "{{ aop }}"
      cloud: alta3cloud
      name: demorouter
      network: public
      interfaces:
        - demo-net-subnet
