---
- name: A playbook to UL cirros images to OpenStack
  hosts: localhost
  #connection: local

  vars:
    urltocirros: https://download.cirros-cloud.net/0.5.1/cirros-0.5.1-x86_64-disk.img
    #img_to_dl: "https://cloud-images.ubuntu.com/focal/20200322/focal-server-cloudimg-amd64-disk-kvm.img"
    ansible_python_interpreter: "/usr/bin/python"
    #tempdir: "~/image_temp/"
    #imgname: "{{ img_to_dl.split('/')[-1] }}"
    #imgdate: "{{ img_to_dl.split('/')[-2] }}"

  tasks:
  - name: Create a temp folder to DL to
    file:
      state: directory
      path: /home/centos/tempimg/

    #download image that will be uploaded to OpenStack Glance
  - name: Download the image
    get_url:
      url: "{{ urltocirros }}"
      dest: /home/centos/tempimg/

    # upload to Openstack Glance (image service)
  - name: Upload the image
    os_image:
      cloud: alta3cloud
      name: cirros-05
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /home/centos/tempimg/cirros-0.5.1-x86_64-disk.img
      #kernel:
      #ramdisk: 
      properties:
        cpu_arch: x86_64
        distro: ubuntu
        
    #Determine if checksum on upload matches what we expected
    #Delete the temp directory
  - name: Remove a temp folder containing the image on the local controller
    file: 
      state: absent
      path: /home/centos/tempimg/
